<?php

namespace App\Utils;

class LanguagesUtils
{
    public static function codeToName(string $code): string
    {
        return self::languages()[strtolower($code)] ?? '';
    }

    public static function nameToCode(string $name): string
    {
        return array_search(strtolower($name), self::languages()) ?? '';
    }

    public static function codes(): array
    {
        return array_keys(self::languages());
    }

    public static function names(): array
    {
        return array_values(self::languages());
    }

    public static function languages(): array
    {
        return [
            "aa" => "afar",
            "ab" => "abkhazian",
            "ae" => "avestan",
            "af" => "afrikaans",
            "ak" => "akan",
            "am" => "amharic",
            "an" => "aragonese",
            "ar" => "arabic",
            "as" => "assamese",
            "av" => "avaric",
            "ay" => "aymara",
            "az" => "azerbaijani",
            "ba" => "bashkir",
            "be" => "belarusian",
            "bg" => "bulgarian",
            "bh" => "bihari",
            "bi" => "bislama",
            "bm" => "bambara",
            "bn" => "bengali",
            "bo" => "tibetan",
            "br" => "breton",
            "bs" => "bosnian",
            "ca" => "catalan",
            "ce" => "chechen",
            "ch" => "chamorro",
            "co" => "corsican",
            "cr" => "cree",
            "cs" => "czech",
            "cu" => "church slavic",
            "cv" => "chuvash",
            "cy" => "welsh",
            "da" => "danish",
            "de" => "german",
            "dv" => "divehi",
            "dz" => "dzongkha",
            "ee" => "ewe",
            "el" => "greek",
            "en" => "english",
            "eo" => "esperanto",
            "es" => "spanish",
            "et" => "estonian",
            "eu" => "basque",
            "fa" => "persian",
            "ff" => "fulah",
            "fi" => "finnish",
            "fj" => "fijian",
            "fo" => "faroese",
            "fr" => "french",
            "fy" => "western frisian",
            "ga" => "irish",
            "gd" => "scots gaelic",
            "gl" => "galician",
            "gn" => "guarani",
            "gu" => "gujarati",
            "gv" => "manx",
            "ha" => "hausa",
            "he" => "hebrew",
            "hi" => "hindi",
            "ho" => "hiri motu",
            "hr" => "croatian",
            "ht" => "haitian",
            "hu" => "hungarian",
            "hy" => "armenian",
            "hz" => "herero",
            "ia" => "interlingua",
            "id" => "indonesian",
            "ie" => "interlingue",
            "ig" => "igbo",
            "ii" => "sichuan yi",
            "ik" => "inupiaq",
            "io" => "ido",
            "is" => "icelandic",
            "it" => "italian",
            "iu" => "inuktitut",
            "ja" => "japanese",
            "jv" => "javanese",
            "ka" => "georgian",
            "kg" => "kongo",
            "ki" => "kikuyu",
            "kj" => "kuanyama",
            "kk" => "kazakh",
            "kl" => "kalaallisut",
            "km" => "central khmer",
            "kn" => "kannada",
            "ko" => "korean",
            "kr" => "kanuri",
            "ks" => "kashmiri",
            "ku" => "kurdish",
            "kv" => "komi",
            "kw" => "cornish",
            "ky" => "kirghiz",
            "la" => "latin",
            "lb" => "luxembourgish",
            "lg" => "ganda",
            "li" => "limburgan",
            "ln" => "lingala",
            "lo" => "lao",
            "lt" => "lithuanian",
            "lu" => "luba-katanga",
            "lv" => "latvian",
            "mg" => "malagasy",
            "mh" => "marshallese",
            "mi" => "maori",
            "mk" => "macedonian",
            "ml" => "malayalam",
            "mn" => "mongolian",
            "mr" => "marathi",
            "ms" => "malay",
            "mt" => "maltese",
            "my" => "burmese",
            "na" => "nauru",
            "nb" => "norwegian bokmal",
            "nd" => "ndebele, north",
            "ne" => "nepali",
            "ng" => "ndonga",
            "nl" => "dutch",
            "nn" => "norwegian nynorsk",
            "no" => "norwegian",
            "nr" => "ndebele, south",
            "nv" => "navajo",
            "ny" => "chichewa",
            "oc" => "occitan",
            "oj" => "ojibwa",
            "om" => "oromo",
            "or" => "oriya",
            "os" => "ossetian",
            "pa" => "panjabi",
            "pi" => "pali",
            "pl" => "polish",
            "ps" => "pushto",
            "pt" => "portuguese",
            "qu" => "quechua",
            "rm" => "romansh",
            "rn" => "kirundi",
            "ro" => "romanian",
            "ru" => "russian",
            "rw" => "kinyarwanda",
            "sa" => "sanskrit",
            "sc" => "sardinian",
            "sd" => "sindhi",
            "se" => "northern sami",
            "sg" => "sango",
            "si" => "sinhala",
            "sk" => "slovak",
            "sl" => "slovenian",
            "sm" => "samoan",
            "sn" => "shona",
            "so" => "somali",
            "sq" => "albanian",
            "sr" => "serbian",
            "ss" => "swati",
            "st" => "sotho, southern",
            "su" => "sundanese",
            "sv" => "swedish",
            "sw" => "swahili",
            "ta" => "tamil",
            "te" => "telugu",
            "tg" => "tajik",
            "th" => "thai",
            "ti" => "tigrinya",
            "tk" => "turkmen",
            "tl" => "tagalog",
            "tn" => "tswana",
            "to" => "tonga",
            "tr" => "turkish",
            "ts" => "tsonga",
            "tt" => "tatar",
            "tw" => "twi",
            "ty" => "tahitian",
            "ug" => "uighur",
            "uk" => "ukrainian",
            "ur" => "urdu",
            "uz" => "uzbek",
            "ve" => "venda",
            "vi" => "vietnamese",
            "vo" => "volapuk",
            "wa" => "walloon",
            "wo" => "wolof",
            "xh" => "xhosa",
            "yi" => "yiddish",
            "yo" => "yoruba",
            "za" => "zhuang",
            "zh" => "chinese",
            "zu" => "zulu"
        ];
    }
}
